# Generated by Django 4.2.26 on 2025-12-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newslettersubscription_page_socialmedialink_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='credit-card', max_length=50),
        ),
    ]
