# Generated by Django 4.2.26 on 2025-12-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_water_resistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='e.g., Leather, Canvas, Mesh', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sole_type',
            field=models.CharField(blank=True, help_text='e.g., Rubber, EVA', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g., 250g per shoe', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='comfort_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='true_to_size',
            field=models.CharField(blank=True, choices=[('small', 'Runs Small'), ('true', 'True to Size'), ('large', 'Runs Large')], max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='width_feedback',
            field=models.CharField(blank=True, choices=[('narrow', 'Too Narrow'), ('perfect', 'Perfect Width'), ('wide', 'Too Wide')], max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='would_recommend',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('navy', 'Navy Blue'), ('grey', 'Grey'), ('beige', 'Beige'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], max_length=50)),
                ('size', models.CharField(choices=[('6', 'UK 6'), ('7', 'UK 7'), ('8', 'UK 8'), ('9', 'UK 9'), ('10', 'UK 10'), ('11', 'UK 11'), ('12', 'UK 12')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('color_image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.product')),
            ],
            options={
                'ordering': ['color', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
